apiVersion: v2
appVersion: "1.0"
description: A Helm chart for cpo-case-payment-orders-api App
name: cpo-case-payment-orders-api
home: https://github.com/hmcts/cpo-case-payment-orders-api
version: 0.1.14
maintainers:
  - name: HMCTS cpo team
dependencies:
  - name: java
    version: 5.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
